### ISSUE TITLE
Meta Cleanup Issue

### ISSUE THREAD

**Issue by koustuvsinha** [facebookresearch/online_dialog_eval#2]
Cleaning up repo gearing for the public release for ACL 2020. 

- [x] Clean up notebook #1 
- [x] Clean up .zip files
- [x] Remove [Seq2Seq](https://github.com/fairinternal/online_dialog_eval/tree/master/Seq2Seq) folder
- [x] Remove backup folder
